language: en
pipeline: supervised_embeddings
policies:
- name: AugmentedMemoizationPolicy
- name: EmbeddingPolicy
  max_history: 2
  batch_strategy: sequence
  epochs: 100
  evaluate_on_num_examples: 0
- name: FormPolicy
