language: en
pipeline: supervised_embeddings
policies:
#- name: KerasPolicy
#  epochs: 200
#  max_history: 1
#- name: MemoizationPolicy
#  max_history: 1
#- name: FallbackPolicy
#  nlu_threshold: 0.63
- name: AugmentedMemoizationPolicy
- name: EmbeddingPolicy
  max_history: 2
  batch_strategy: "sequence"
  epochs: 100
  evaluate_on_num_examples: 0
- name: FormPolicy
