# export RASA_X_VERSION=0.22.1
# export RASA_SDK_VERSION=1.4.0
# docker-compose -f docker-compose-local.yml up -d
# docker-compose -f docker-compose-local.yml run rasa bash
# docker-compose -f docker-compose-local.yml exec rasa bash
version: "3.4"

services:
  rasa-x:
    image: rasax:${RASA_X_VERSION}
    environment:
      - RASA_HOME=/app
#      - RASA_MODEL_SERVER="http://localhost:5002/api/projects/default/models/tags/production"
#      - RASA_X_TOKEN=3fa3e3PdL6MXN2
#      - RASA_MODEL_PULL_INTERVAL=10
    ports:
      - "5005:5005"
      - "5002:5002"
#      - "8022:22"
#      - "8888:8888" 
    volumes:
      - ./:/app
    command: rasa x --no-prompt --endpoints endpoints-local.yml --credentials credentials-local.yml --port 5005 --cors "*" --debug
#    command: /app/rasax.sh
  app:
    image: rasa/rasa-sdk:${RASA_SDK_VERSION}
    volumes:
      - "./actions:/app/actions"
    ports:
      - "5055:5055"
