  
name: Build and Deploy
on: [push]

jobs:
  build-images:
    name: Build and Push Images
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Show python versions
      run: |
        python --version
        python3 --version
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.5
    - name: Show python versions again
      run: |
        python --version
        python3 --version
    - name: Install dependencies
      working-directory: ${{ github.workspace }}/actions
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
    - name: Type Checking
      working-directory: ${{ github.workspace }}
      run: |
        make types
    - name: Test Training Stories
      working-directory: ${{ github.workspace }}
      run: |
        rasa train core --config augmentedmemo-only.yml --augmentation 0 --quiet
        rasa test core --fail-on-prediction-errors --quiet
    - name: Build and Push Action Image
      working-directory: ${{ github.workspace }}
      env:
        gcr_docker_auth: ${{ secrets.gcr_docker_auth}}
      run: |
        docker login -u _json_key -p "$(cat gcr_docker_auth.json)" https://gcr.io
        docker pull gcr.io/replicated-test/rasa-demo:latest || true